# thing_space_connectivity_management_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'thing_space_connectivity_management_api'
require_relative '../test_helper'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include ThingSpaceConnectivityManagementApi

  # Create configuration and set any test parameters
  def config
    @config ||= Configuration.new
  end
end
