# thing_space_connectivity_management_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class ServicePlansControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    token = OAuth2.authorize config
    config = config().clone_with o_auth_token: token

    @response_catcher = HttpResponseCatcher.new
    @controller = ServicePlansController.new config, http_call_back: @response_catcher
  end

  # Returns a list of all data service plans that are associated with a specified billing account. When you send a request to /devices/actions/activate to activate a line of service you must specify the code for one of the service plans associated with your account.
  def test_list_account_service_plans()
    # Parameters for the API call
    aname = '0252012345-00001'

    # Perform the API call through the SDK function
    result = @controller.list_account_service_plans(aname)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(TestHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '[{"name":"2MSHR5GB","code":"M2MSHR5GB","sizeKb":0,"carrierServicePlanCo'\
      'de":"84638"},{"name":"TNTL200TALK","code":"NTL200TALK","sizeKb":0,"carr'\
      'ierServicePlanCode":"74644"}]'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body))
  end

end
