# thing_space_connectivity_management_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  # The current status of the callback response.
  class RequestStatusEnum
    REQUEST_STATUS_ENUM = [
      # TODO: Write general description for PENDING
      PENDING = 'Pending'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'Success'.freeze,

      # TODO: Write general description for FAILURE
      FAILURE = 'Failure'.freeze
    ].freeze
  end
end
